/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eaf1ff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#8ef5e3',
        'on-primary-fixed': '#001b3e',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-tertiary-fixed-variant': '#613e33',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-lowest': '#ffffff',
        tertiary: '#795347',
        'tertiary-container': '#946b5e',
        'on-primary-container': '#fefcff',
        'surface-tint': '#285eaa',
        'on-primary': '#ffffff',
        'inverse-surface': '#223144',
        'on-primary-fixed-variant': '#00458e',
        'on-surface-variant': '#3d4946',
        'primary-fixed-dim': '#aac7ff',
        'outline-variant': '#bdc9c5',
        'primary-container': '#4374c2',
        'secondary-fixed-dim': '#71d8c7',
        'surface-container-highest': '#d4e4fd',
        'on-error': '#ffffff',
        'on-surface': '#0c1c2e',
        primary: '#245ba7',
        outline: '#6d7a77',
        'tertiary-fixed-dim': '#edbbac',
        'on-tertiary-fixed': '#2f140b',
        'surface-variant': '#d4e4fd',
        'surface-dim': '#cbdbf4',
        error: '#ba1a1a',
        'on-secondary-fixed': '#00201c',
        'on-secondary-container': '#007165',
        'on-background': '#0c1c2e',
        'error-container': '#ffdad6',
        'surface-bright': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'on-tertiary-container': '#fffbff',
        'primary-fixed': '#d7e3ff',
        secondary: '#006b5f',
        surface: '#f8f9ff',
        'inverse-primary': '#aac7ff',
        'on-secondary-fixed-variant': '#005047',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdbd0',
        'secondary-container': '#8ef5e3',
        'peach-muted': '#FFCCBC',
        'chekhov-ice': '#e0f2f1',
        'ice-blue': '#D3E3FC',
        'scholar-teal': '#006b5f',
      },
      fontFamily: {
        headline: ['var(--font-newsreader)', 'serif'],
        body: ['var(--font-newsreader)', 'serif'],
        label: ['var(--font-jetbrains-mono)', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '0px',
      },
    },
  },
  plugins: [],
};
